Create an account
AlenaHavaleshko/Beetroot-Academy pull request #10
Opened 2023-03-28 20:53 UTC by AlenaHavaleshko

2023-04-01 15:56 UTC, besvova490 requested changes

2023-04-01 15:56 UTC, besvova490 commented on lesson-16-style-forms/index.html
> +            <input class="field-items" type="text" id="last-name" name="last-name" required>
додай закриваючий слеш в кінець інпута <input class="field-items" type="text" id="last-name" name="last-name" required/> (глянуш по всьому документу)

2023-04-01 15:56 UTC, besvova490 commented on lesson-16-style-forms/index.html
> +                  class="select-color">Select</span></option>
тут краще зробити через option disabled

2023-04-01 15:56 UTC, besvova490 commented on lesson-16-style-forms/styles/style.css
> +  height: 540px;
краще вирівняти форму через флек а не через absolute

2023-04-01 15:56 UTC, besvova490 commented on lesson-16-style-forms/index.html
> +          <span>Have an account?</span>
ці два спани мали б бути посиланнями

2023-04-01 15:56 UTC, besvova490 commented on lesson-16-style-forms/index.html
> +            <label class="width-auto label-item" for="male">Male</label>
label привязується по id зараз в тебе якщо клікнути на лейбл то радіо інпут не вибиреться
++ цей інпуте треба перезаписати як ми робили сьогодні на уроці

2023-04-14 21:28 UTC, AlenaHavaleshko commented on lesson-16-style-forms/styles/style.css
> +  height: 540px;
done

2023-04-14 21:28 UTC, AlenaHavaleshko commented on lesson-16-style-forms/index.html
> +                  class="select-color">Select</span></option>
done

2023-04-14 21:36 UTC, AlenaHavaleshko commented on lesson-16-style-forms/index.html
> +                  class="select-color">Select</span></option>
done

2023-04-14 21:36 UTC, merged