Final progect Novikov
AlenaHavaleshko/Beetroot-Academy pull request #4
Opened 2023-03-09 21:53 UTC by AlenaHavaleshko

2023-03-12 12:34 UTC, besvova490 requested changes

2023-03-12 12:34 UTC, besvova490 commented on lesson-5-figma/index.html
> +      <div class="navbar-menu">
додай nav замість div

2023-03-12 12:34 UTC, besvova490 commented on lesson-5-figma/index.html
> +                  <img src="./images/Star.jpg" alt="rating 1">
поправ img тег він є непарним тому його треба закривати <img> => <img/> (глянеш по всьому файлі)

2023-03-13 13:03 UTC, AlenaHavaleshko commented on lesson-5-figma/index.html
> +      <div class="navbar-menu">
done

2023-03-13 13:03 UTC, AlenaHavaleshko commented on lesson-5-figma/index.html
> +                  <img src="./images/Star.jpg" alt="rating 1">
done

2023-03-13 13:04 UTC, merged