Added all code
AlenaHavaleshko/Beetroot-Academy pull request #6
Opened 2023-03-17 12:17 UTC by AlenaHavaleshko

2023-03-19 13:37 UTC, besvova490 requested changes

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +.header__logo {}
видали порожній клас

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +.header__navigation-list {
додай поррожню лінію перед імям класа (глянеш по всьому документу)

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +  Width: 1088px;
Width => width пишемо з маленької взагалі всі css властивості пишуться з маленької букви глянеш по всьому файлу

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +  Top:1px;
властивості top, left, right, bottom не працюють без position: absolute; тому їх краще видалити так як вони нічого не роблять

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +  .header__button-sign-up {
придире лишній відступ перед імям класа

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +  height: 91px;
фіксовану ширину текстовим блокам не бажано задавайти бо якщотекст буде більший то його обріже

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +  margin: 50px 0 31px 0;
цей марджин краще видалити бо нидній його і так перезапише

2023-03-19 13:37 UTC, besvova490 commented on lesson-9-BAM/styles/styles.css
> +.footer__item-button {
порожні класи краще видаляти

2023-03-21 21:34 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +.header__logo {}
Done

2023-03-21 21:37 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +.header__navigation-list {
Done

2023-03-21 21:38 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +  Width: 1088px;
Done

2023-03-21 21:45 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +  Top:1px;
deleted

2023-03-21 21:48 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +  height: 91px;
redundant positions removed

2023-03-21 21:52 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +  .header__button-sign-up {
done

2023-03-21 21:52 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +  margin: 50px 0 31px 0;
Done

2023-03-21 21:52 UTC, AlenaHavaleshko commented on lesson-9-BAM/styles/styles.css
> +.footer__item-button {
Deleted

2023-03-21 21:52 UTC, merged